### ISSUE TITLE
XML Settings 

### ISSUE THREAD

**Issue by ElroieRoash** [College-Maze/Maze#9]
In project Maze.IO 
Create two Class ConfigurationManager & Properties.
ConfigurationManager responsibilities are to
1. Save all Properties to xml file (the xml path should be inside the application path - there we will definitly have permissions to write).

2. retrieve Properties- This method should go the xml path and retrieve it and make it to be Properties class and return this value.

Properties class:
should implements/extends Seralizable
should contains all system configuration (meanwhile you can put here only threadAmount ).

to check it:
it the main class call to the ConfigurationManager.save(Properties p)
and see that this xml file is saved/ overwritten.

psuedo code:
ConfigurationManager mgr = new ConfigurationManager(c:\boolbool.xml);
Properties p = new Properties();
p.setThreads(4)
mgr.save(p);

**Comment by NimrodDickler** [comment]
Done
